### ISSUE TITLE
Reporte de práctica: conexión a bases de datos.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-check_team#1]
[Conexion.a.base.de.datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-check_team/files/6771017/Conexion.a.base.de.datos.pdf)

**Comment by Edwin38H** [comment]
cal: 19

**Comment by Edwin38H** [comment]
calificacion : 20
Bien hecho compañeros

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
